### PR TITLE
unsuck the code

### PR DESCRIPTION
**Pull request by crwn1337**

### CODE REVIEW

**Comment by iProgramMC** [comment]
That doesn't really make it look better, the overusage of "var" instead of specifying the actual type can really throw the compiler off. Also, good point, it was anim length (milliseconds), and will update it myself. The change for DecodeName was really not needed. I will change that and the .gitignore

**Comment by crwn1337** [comment]
https://www.dofactory.com/reference/csharp-coding-standards

**Comment by crwn1337** [comment]
the var doesnt throw the compiler off, unless you do shit like `short i = 0ull;`
the decodename wasnt changed, i just formatted the entire file.

**Comment by iProgramMC** [comment]
> the var doesnt throw the compiler off, unless you do shit like `short i = 0ull;`
> the decodename wasnt changed, i just formatted the entire file.

You used "var" as "string"

**Comment by iProgramMC** [comment]
also what's this 
image

**Comment by crwn1337** [comment]
[var as string](https://i.imgur.com/mW9bR2E.png)
no point in continuing this

**Pull request closed without merging**
